### PR TITLE
fde: Scroll elements if they don't fit

### PR DESCRIPTION
**Pull request by crawfxrd**
Prevent elements from running off the bottom of the form by limiting the number that are rendered. Up/down arrows are rendered on the right of the form to indicate more items.

Screenshot from 2020-07-28 11-56-58

Space below last element is to account for the footer growing to 2 rows.

### CODE REVIEW

**Comment by jacobgkau** [comment]
I'm seeing the down arrow appear in the bottom right of the screen all the time, even on pages that don't need to be scrolled. Since the point of the arrows are to indicate more items, is that feasible to fix?

**Comment by crawfxrd** [comment]
Fixed the condition. Down arrow should behave correctly now.

**Comment by crawfxrd** [comment]
I moved the down arrow up slightly. It should be square and match the up arrow now.

**Comment by jacobgkau** [comment]
Still looks good to me on the darp6. Arrow before it was moved:

arrow-1-small

After:

arrow-2-small

I was curious what would happen if a filename was too long for one line, and it just cuts off (which seems fine to me, since a single file or directory name would not usually be this long):

IMG_20200728_154338

**Pull request merged**
